export const users = [
    {
        id: 1,
        firstName: 'Terry',
        lastName: 'Medhurst',
        maidenName: 'Smitham',
        age: 50,
        gender: 'male',
        email: 'atuny0@sohu.com',
        phone: '+63 791 675 8914',
        username: 'atuny0',
        password: '9uQFF1Lh',
        birthDate: '2000-12-25',
        image: 'https://robohash.org/Terry.png?set=set4',
        ip: '117.29.86.254',
        address: {
            address: '1745 T Street Southeast',
            city: 'Washington',
            coordinates: {
                lat: 38.867033,
                lng: -76.979235,
            },
            postalCode: '20020',
            state: 'DC',
        },
        company: {
            address: {
                address: '629 Debbie Drive',
                city: 'Nashville',
                coordinates: {
                    lat: 36.208114,
                    lng: -86.58621199999999,
                },
                postalCode: '37076',
                state: 'TN',
            },
            department: 'Marketing',
            name: "Blanda-O'Keefe",
            title: 'Help Desk Operator',
        },
    },
    {
        id: 2,
        firstName: 'Sheldon',
        lastName: 'Quigley',
        maidenName: 'Cole',
        age: 28,
        gender: 'male',
        email: 'hbingley1@plala.or.jp',
        phone: '+7 813 117 7139',
        username: 'hbingley1',
        password: 'CQutx25i8r',
        birthDate: '2003-08-02',
        image: 'https://robohash.org/Sheldon.png?set=set4',
        ip: '253.240.20.181',
        address: {
            address: '6007 Applegate Lane',
            city: 'Louisville',
            coordinates: {
                lat: 38.1343013,
                lng: -85.6498512,
            },
            postalCode: '40219',
            state: 'KY',
        },
        company: {
            address: {
                address: '8821 West Myrtle Avenue',
                city: 'Glendale',
                coordinates: {
                    lat: 33.5404296,
                    lng: -112.2488391,
                },
                postalCode: '85305',
                state: 'AZ',
            },
            department: 'Services',
            name: 'Aufderhar-Cronin',
            title: 'Senior Cost Accountant',
        },
    },
    {
        id: 3,
        firstName: 'Terrill',
        lastName: 'Hills',
        maidenName: 'Hoeger',
        age: 38,
        gender: 'male',
        email: 'rshawe2@51.la',
        phone: '+63 739 292 7942',
        username: 'rshawe2',
        password: 'OWsTbMUgFc',
        birthDate: '1992-12-30',
        image: 'https://robohash.org/Terrill.png?set=set4',
        ip: '205.226.160.3',
        address: {
            address: '560 Penstock Drive',
            city: 'Grass Valley',
            coordinates: {
                lat: 39.213076,
                lng: -121.077583,
            },
            postalCode: '95945',
            state: 'CA',
        },
        company: {
            address: {
                address: '18 Densmore Drive',
                city: 'Essex',
                coordinates: {
                    lat: 44.492953,
                    lng: -73.101883,
                },
                postalCode: '05452',
                state: 'VT',
            },
            department: 'Marketing',
            name: 'Lindgren LLC',
            title: 'Mechanical Systems Engineer',
        },
    },
    {
        id: 4,
        firstName: 'Miles',
        lastName: 'Cummerata',
        maidenName: 'Maggio',
        age: 49,
        gender: 'male',
        email: 'yraigatt3@nature.com',
        phone: '+86 461 145 4186',
        username: 'yraigatt3',
        password: 'sRQxjPfdS',
        birthDate: '1969-01-16',
        image: 'https://robohash.org/Miles.png?set=set4',
        ip: '243.20.78.113',
        address: {
            address: '150 Carter Street',
            city: 'Manchester',
            coordinates: {
                lat: 41.76556000000001,
                lng: -72.473091,
            },
            postalCode: '06040',
            state: 'CT',
        },
        company: {
            address: {
                address: '210 Green Road',
                city: 'Manchester',
                coordinates: {
                    lat: 41.7909099,
                    lng: -72.51195129999999,
                },
                postalCode: '06042',
                state: 'CT',
            },
            department: 'Business Development',
            name: 'Wolff and Sons',
            title: 'Paralegal',
        },
    },
    {
        id: 5,
        firstName: 'Mavis',
        lastName: 'Schultz',
        maidenName: 'Yundt',
        age: 38,
        gender: 'male',
        email: 'kmeus4@upenn.edu',
        phone: '+372 285 771 1911',
        username: 'kmeus4',
        password: 'aUTdmmmbH',
        birthDate: '1968-11-03',
        image: 'https://robohash.org/Mavis.png?set=set4',
        ip: '103.72.86.183',
        address: {
            address: '2721 Lindsay Avenue',
            city: 'Louisville',
            coordinates: {
                lat: 38.263793,
                lng: -85.700243,
            },
            postalCode: '40206',
            state: 'KY',
        },
        company: {
            address: {
                address: '8398 West Denton Lane',
                city: 'Glendale',
                coordinates: {
                    lat: 33.515353,
                    lng: -112.240812,
                },
                postalCode: '85305',
                state: 'AZ',
            },
            department: 'Support',
            name: 'Adams Inc',
            title: 'Web Developer I',
        },
    },
    {
        id: 8,
        firstName: 'Ewell',
        lastName: 'Mueller',
        maidenName: 'Durgan',
        age: 29,
        gender: 'male',
        email: 'ggude7@chron.com',
        phone: '+86 946 297 2275',
        username: 'ggude7',
        password: 'MWwlaeWcOoF6',
        birthDate: '1964-08-24',
        image: 'https://robohash.org/Ewell.png?set=set4',
        ip: '91.200.56.127',
        address: {
            address: '5601 West Crocus Drive',
            city: 'Glendale',
            coordinates: {
                lat: 33.6152469,
                lng: -112.179737,
            },
            postalCode: '85306',
            state: 'AZ',
        },
        company: {
            address: {
                address: '81 Seaton Place Northwest',
                city: 'Washington',
                coordinates: {
                    lat: 38.9149499,
                    lng: -77.01170259999999,
                },
                postalCode: '20001',
                state: 'DC',
            },
            department: 'Services',
            name: 'Corkery, Reichert and Hodkiewicz',
            title: 'Clinical Specialist',
        },
    },
    {
        id: 9,
        firstName: 'Demetrius',
        lastName: 'Corkery',
        maidenName: 'Gleason',
        age: 22,
        gender: 'male',
        email: 'nloiterton8@aol.com',
        phone: '+86 356 590 9727',
        username: 'nloiterton8',
        password: 'HTQxxXV9Bq4',
        birthDate: '1971-03-11',
        image: 'https://robohash.org/Demetrius.png?set=set4',
        ip: '78.170.185.120',
        address: {
            address: '5403 Illinois Avenue',
            city: 'Nashville',
            coordinates: {
                lat: 36.157077,
                lng: -86.853827,
            },
            postalCode: '37209',
            state: 'TN',
        },
        company: {
            address: {
                address: '12245 West 71st Place',
                city: 'Arvada',
                coordinates: {
                    lat: 39.8267078,
                    lng: -105.1366798,
                },
                postalCode: '80004',
                state: 'CO',
            },
            department: 'Human Resources',
            name: 'Gorczany Group',
            title: 'Community Outreach Specialist',
        },
    },
    {
        id: 11,
        firstName: 'Marcel',
        lastName: 'Jones',
        maidenName: 'Smith',
        age: 39,
        gender: 'male',
        email: 'acharlota@liveinternet.ru',
        phone: '+967 253 210 0344',
        username: 'acharlota',
        password: 'M9lbMdydMN',
        birthDate: '1961-09-12',
        image: 'https://robohash.org/Marcel.png?set=set4',
        ip: '137.235.164.173',
        address: {
            address: '2203 7th Street Road',
            city: 'Louisville',
            coordinates: {
                lat: 38.218107,
                lng: -85.779006,
            },
            postalCode: '40208',
            state: 'KY',
        },
        company: {
            address: {
                address: '308 Woodleaf Court',
                city: 'Glen Burnie',
                coordinates: {
                    lat: 39.1425931,
                    lng: -76.6238441,
                },
                postalCode: '21061',
                state: 'MD',
            },
            department: 'Business Development',
            name: 'Kuhn-Harber',
            title: 'Account Executive',
        },
    },
];
